import type { Metadata } from "next";
import "./globals.css";
import ApolloWrapper from "./api/graphql/ApolloWrappre";
import SessionProviderWrapper from "@/providers/SessionProviderWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <SessionProviderWrapper>
          <ApolloWrapper>{children}</ApolloWrapper>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
